"""Artifacts: every run leaves a complete, inspectable trail on disk.

A result nobody can audit is not evidence. Each run gets its own
directory holding the environment, the plan, the policy decision, every
measurement, the verdict, and the rollback record.
"""

from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass
from typing import Any

RUNS_DIRNAME = os.path.join(".infra-team", "runs")


def _json_default(obj: Any) -> Any:
    if hasattr(obj, "to_dict"):
        return obj.to_dict()
    return str(obj)


@dataclass
class RunArtifacts:
    """Filesystem handle for one run's evidence bundle."""

    root: str
    run_id: str

    @property
    def path(self) -> str:
        return os.path.join(self.root, RUNS_DIRNAME, self.run_id)

    def ensure(self) -> None:
        os.makedirs(self.path, exist_ok=True)

    def write_json(self, name: str, payload: Any) -> str:
        self.ensure()
        target = os.path.join(self.path, name)
        with open(target, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2, default=_json_default)
            fh.write("\n")
        return target

    def write_text(self, name: str, text: str) -> str:
        self.ensure()
        target = os.path.join(self.path, name)
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(text)
        return target

    def append_text(self, name: str, text: str) -> str:
        self.ensure()
        target = os.path.join(self.path, name)
        with open(target, "a", encoding="utf-8") as fh:
            fh.write(text)
        return target

    def log_path(self, name: str = "transcript.log") -> str:
        self.ensure()
        return os.path.join(self.path, name)


def new_run(root: str, run_id: str | None = None) -> RunArtifacts:
    """Create a fresh, timestamped run directory."""
    run_id = run_id or time.strftime("%Y%m%d-%H%M%S")
    art = RunArtifacts(root=root, run_id=run_id)
    art.ensure()
    return art


def write_recipe(
    art: RunArtifacts,
    verdict_dict: dict[str, Any],
    spec: dict[str, Any],
    environment: dict[str, Any],
) -> str:
    """Write the human-reproducible winning configuration.

    Deliberately plain text: a user should be able to read it and rerun
    the command by hand without trusting this tool.
    """
    draft = spec.get("draft_model")
    block = spec.get("draft_block_size")

    lines = [
        "# selected_recipe.yaml",
        "# Generated by the virtual AI Infra team from a real measured run.",
        f"# run_id: {art.run_id}",
        "",
        "selection:",
        f"  candidate: {verdict_dict['selected_id']}",
        f"  accepted: {str(verdict_dict['accepted']).lower()}",
        f"  reason: \"{verdict_dict['reason']}\"",
        f"  baseline_tokens_per_second: {verdict_dict['baseline_tps']}",
        f"  selected_tokens_per_second: {verdict_dict['selected_tps']}",
        f"  speedup_percent: {verdict_dict['speedup_percent']}",
        "",
        "runtime:",
        "  engine: mlx-vlm",
        f"  target_model: {spec.get('target_model')}",
        f"  draft_model: {draft if draft else 'null'}",
        f"  draft_kind: {spec.get('draft_kind') or 'null'}",
        f"  draft_block_size: {block if block else 'null'}",
        f"  temperature: {spec.get('temperature')}",
        f"  enable_thinking: {str(spec.get('enable_thinking')).lower()}",
        "",
        "environment:",
        f"  chip: {environment.get('chip')}",
        f"  gpu_cores: {environment.get('gpu_cores')}",
        f"  unified_memory_gb: {environment.get('unified_memory_gb')}",
        f"  macos: {environment.get('macos_version')}",
        f"  mlx: {(environment.get('packages') or {}).get('mlx')}",
        f"  mlx_vlm: {(environment.get('packages') or {}).get('mlx-vlm')}",
        "",
        "reproduce:",
    ]

    if draft:
        cmd = (
            f"  - mlx_vlm.generate --model {spec.get('target_model')}"
            f" --draft-model {draft}"
        )
        if block:
            cmd += f" --draft-block-size {block}"
        cmd += ' --prompt "Write a quicksort in Python." --max-tokens 256 --temperature 0'
        lines.append(cmd)
        server = (
            f"  - mlx_vlm.server --model {spec.get('target_model')}"
            f" --draft-model {draft}"
        )
        if block:
            server += f" --draft-block-size {block}"
        lines.append(server)
    else:
        lines.append(
            f"  - mlx_vlm.generate --model {spec.get('target_model')}"
            ' --prompt "Write a quicksort in Python." --max-tokens 256'
            " --temperature 0"
        )
        lines.append(f"  - mlx_vlm.server --model {spec.get('target_model')}")

    return art.write_text("selected_recipe.yaml", "\n".join(lines) + "\n")


def write_rollback(
    art: RunArtifacts,
    baseline_spec: dict[str, Any],
    verdict_dict: dict[str, Any],
) -> str:
    """Record how to get back to the baseline.

    Rollback is trivial here by design: candidates only ever ran in
    throwaway subprocesses, so nothing persistent was mutated.
    """
    payload = {
        "baseline_retained": True,
        "baseline_spec": baseline_spec,
        "optimization_accepted": verdict_dict["accepted"],
        "rollback_action": (
            "Discard selected_recipe.yaml and serve the baseline spec below."
        ),
        "rollback_command": (
            f"mlx_vlm.server --model {baseline_spec.get('target_model')}"
        ),
        "mutations_performed": [],
        "notes": (
            "No system state was modified. Each candidate ran in an isolated "
            "subprocess that exited before the next candidate started, so "
            "reverting requires no cleanup."
        ),
    }
    return art.write_json("rollback.json", payload)
